import "./globals.css";
import { Inter, Poppins } from 'next/font/google';
import { Metadata } from 'next';
import Header from '@/components/Header/index';
import Footer from '@/components/Footer/index';

const inter = Inter({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-inter',
});

const poppins = Poppins({
  subsets: ['latin'],
  display: 'swap',
  weight: ['400', '500', '600', '700'],
  variable: '--font-poppins',
});

// Typed metadata export
export const metadata: Metadata = {
  title: "Orange Circle",
  description: "Generated by create next app",
};

// Typed children prop
interface RootLayoutProps {
  children: React.ReactNode;
}

export default function RootLayout({ children }: RootLayoutProps) {
  return (
      <html lang="en" className={`${inter.variable} ${poppins.variable}`}>
      <body>
        <Header />
        {children}
        <Footer />
      </body>
      </html>
  );
}
